language: java

#jdk:
#  - openjdk8

sudo: required

dist: trusty

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn cobertura:cobertura

addons:
  sonarcloud:
    organization: "karlscode-github"
    token:
      # encrypted value of your token
      secure: $SONAR_TOKEN

script:
  # other script steps might be done before running the actual analysis.
  - sonar-scanner
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis.

#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -B -e -V -Dmaven.javadoc.skip=true -Dsonar.branch.name=$TRAVIS_BRANCH
  - mvn test -B

cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
  email: false