CREATE SEQUENCE address_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE TABLE address (
    id BIGINT GENERATED BY DEFAULT AS SEQUENCE address_id_seq PRIMARY KEY,
    street VARCHAR(255) NOT NULL,
    number_address VARCHAR(255) NOT NULL,
    complement VARCHAR(255) NOT NULL,
    neighborhood VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    id_person BIGINT NOT NULL,
    FOREIGN KEY (id_person) REFERENCES person(id)
);